### PR TITLE
Update to 2022.6.1

### PR DESCRIPTION
**Pull request by eriknw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eriknw** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
The CI for this did not run through on main...

**Comment by jakirkham** [comment]
It appears to [have completed]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=526219&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d ) and [the package is available]( https://anaconda.org/conda-forge/python-graphblas/files?version=2022.6.1 ).

Was there another PR this was intended for?

**Comment by h-vetinari** [comment]
No, I had just seen the failing CI on main by chance. Thanks.

**Comment by h-vetinari** [comment]
> No, I had just seen the failing CI on main by chance. Thanks.

Curiously, it is now noted as passing, even...? Pretty sure I did not mix that up, but if so, apologies.

**Comment by jakirkham** [comment]
No worries. Maybe some caching issue?

Didn't know if it was meant to be a reference to `graphblas` instead

**Pull request merged**
