### PR TITLE
Update to 2023.10.0 (change from noarch)

### PR DESCRIPTION
**Pull request by eriknw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eriknw** [comment]
@conda-forge-admin, please rerender

**Comment by eriknw** [comment]
@conda-forge-admin, please rerender

**Comment by eriknw** [comment]
Alright, I think I changed from "noarch" to "arch" correctly. Let's ship it!

**Comment by eriknw** [comment]
oops, this didn't include builds for Python 3.12.

@jakirkham, what's the magic incantation to include Python 3.12? I changed this recipe from noarch so we can skip numba for Python 3.12. All other dependencies support Python 3.12.

**Comment by jakirkham** [comment]
The bot would normally add a migrator for us, but it sees the `numba` requirement (and doesn't parse the selector) so assumes we need that first. As `numba` isn't yet migrated, we haven't seen a migrator PR

https://github.com/conda-forge/python-graphblas-feedstock/blob/0bfc3bf8166b279e32c6de2d5fd7800e1c40f11c/recipe/meta.yaml#L27

Manually copied [the Python 3.12 migrator]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/python312.yaml ) and added it in PR ( https://github.com/conda-forge/python-graphblas-feedstock/pull/20 ) (with a re-render). That will add Python 3.12. Please feel free to push any other changes to that PR

**Comment by eriknw** [comment]
Awesome, thanks @jakirkham! :tada:

**Pull request merged**
